language: python
os:
  - linux
env:
  - TESTING=true DEBUG=true
python:
  - 3.5.2
  - 3.5.3
  - 3.6.3
before_install:
  - pwd
  - sudo apt-get -qq update
  - sudo apt-get install -y libleveldb-dev python3-dev
  - pip install -r requirements.txt
script:
  - pip install coverage==4.5.1
  - coverage run --source=spruned -m unittest discover
after_success:
  - coverage report
  - if [[ $(python3 -V 2>&1) == *"Python 3.6"* ]]; then
      pip install python-coveralls;
      coveralls;
    fi

